version: '2'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile 
      args:
        http_proxy: http://proxy-chain.intel.com:911/
        https_proxy: http://proxy-chain.intel.com:911/
    container_name: webapp-cnt
    image: webapp-img
    ports:
      - "9000:9000"
