version: '3.3'

services:
  web:
    build: 
      context: .
      dockerfile: dockerfile-app
    container_name: dproject-cnt-app
    image: dproject-img-app
    links:
      - db:db
    depends_on:
      - db
    ports:
      - "9000:9000"
  db:
    env-file: db.env
    container_name: dproject-cnt-db
    image: dproject-img-db
    build: 
      context: ./temp
      dockerfile: dockerfile-db
    ports:
      - "5432:5432"
