version: '3.3'

services:
  web:
    container_name: dproject-cnt-app
    image: srinics/django-project:tag2
    links:
      - db:db
    depends_on:
      - db
    ports:
      - "9000:9000"
  db:
    env_file: docker/db.env
    container_name: dproject-cnt-db
    image: srinics/postgres-db:tag1
    ports:
      - "5432:5432"
