version: '3.3'

services:
  web:
    build: 
      context: .
      dockerfile: docker/dockerfile-app
    container_name: dproject-cnt-app
    image: dproject-img-app
    depends_on:
      - db
    ports:
      - "38080:9090"
    networks:
      - mynetwork

  db:
    env_file: docker/db.env
    container_name: dproject-cnt-db
    image: dproject-img-db
    build: 
      context: .
      dockerfile: docker/dockerfile-db
    ports:
      - "5432:5432"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
         
